FROM andreysenov/firebase-tools:latest-node-16

USER root
RUN apt update && apt install -y curl

# Required for pubsub emulator
# https://github.com/firebase/firebase-tools/issues/5256#issuecomment-1383228506
ENV LD_PRELOAD=/lib/libgcompat.so.0

WORKDIR /app
RUN chown -R node:node .
USER node