FROM alexjball/firebase-tools:latest-node-16

USER root
RUN apk update && apk add python3 build-base

USER node
WORKDIR /app

COPY --chown=node package.json yarn.lock ./
COPY --chown=node functions/package.json functions/yarn.lock ./functions/

RUN yarn install