apiVersion: v1
kind: Service
metadata:
  name: typesense-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8108
  selector:
    app: typesense
