apiVersion: apps/v1
kind: Deployment
metadata:
  name: typesense-deployment
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: typesense
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: typesense
    spec:
      containers:
        - name: typesense
          image: typesense/typesense:0.24.0
          ports:
            - containerPort: 8108
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 50Mi
              cpu: 50m
          volumeMounts:
            - mountPath: /app/data
              name: datav
          env:
            - name: TYPESENSE_DATA_DIR
              value: /app/data
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secretName }}"
                  key: api-key
            - name: TYPESENSE_ENABLE_CORS
              value: "true"
      volumes:
        - name: datav
          persistentVolumeClaim:
            claimName: typesense-data
