apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ..

helmCharts:
  - name: app
    # include the traefik CRD's
    includeCRDs: true
    releaseName: prod
    valuesInline:
      apiDomain: api.mapletestimony.org
      storageSize: 10Gi
      storageClassName: linode-block-storage-retain
      secretName: typesense

resources:
  - ./typesense-secrets.yml

patches:
  # https://github.com/traefik/traefik/issues/8786#issuecomment-1237273950
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
    target:
      version: v1
      kind: Deployment
      name: prod-traefik
