# apiDomain is the FQDN of the application.
apiDomain: ""

# storageClassName is the storage class of the typesense data volume.
storageClassName: ""

# secretName is the name of the secret containing secret values.
# The secret must contain these keys:
# api-key: The key to use for the typesense bootstrap key.
secretName: ""

traefik:
  ports:
    websecure:
      tls:
        certResolver: letsencrypt
    web:
      redirectTo: websecure

  deployment:
    initContainers:
      # Traefik ends up saving the acme.json file with 660 permissions. It checks
      # for 600 on startup (???) and this fixes the permissions.
      - name: volume-permissions
        image: busybox:1.31.1
        command: ["sh", "-c", "chmod -Rv 600 /data/* || true"]
        volumeMounts:
          - name: data
            mountPath: /data

  persistence:
    name: data
    path: /data
    enabled: true
    size: 128Mi

  logs:
    general:
      level: DEBUG

  certResolvers:
    letsencrypt:
      email: me@alexjball.com
      httpchallenge:
        entrypoint: "web"
      storage: /data/acme.json
      # Please note that this is the staging Let's Encrypt server.
      # Once you get things working, you should remove that whole line altogether.
      # caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"
