name: "Chromatic"

on: ["push", "pull_request"]

jobs:
  chromatic-deployment:
    if: github.repository_owner == 'codeforboston'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-repo
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: f8618e690599
          exitZeroOnChanges: true
          exitOnceUploaded: true
